public class Bingus {
    public static void main(String[] args) {
        //String was generated by Codex based on an ASCII art input
        String banner = "  ____  _                       \n"
                + " | __ )(_)_ __   __ _ _   _ ___ \n"
                + " |  _ \\| | '_ \\ / _` | | | / __|\n"
                + " | |_) | | | | | (_| | |_| \\__ \\\n"
                + " |____/|_|_| |_|\\__, |\\__,_|___/\n"
                + "                |___/           \n";
        String line = "____________________________________________________________";

        //Message sequence
        System.out.println(line);
        System.out.print(banner);
        System.out.println("Hello! I'm Bingus.");
        System.out.println("What can I do for you?");
        System.out.println(line);
        System.out.println("Bye. Hope to see you again soon!");
        System.out.println(line);
    }
}
