import java.util.Scanner;

/**
 * Starts Bingus and handles simple commands entered at the terminal.
 */
public class Bingus {


    private static final String line = "____________________________________________________________";

    /**
     * Displays the welcome message, echoes commands, and exits on {@code bye}.
     *
     * @param args command-line arguments, which are not used
     */
    public static void main(String[] args) {
        //String was generated by Codex based on an ASCII art input
        String banner = "  ____  _                       \n"
                + " | __ )(_)_ __   __ _ _   _ ___ \n"
                + " |  _ \\| | '_ \\ / _` | | | / __|\n"
                + " | |_) | | | | | (_| | |_| \\__ \\\n"
                + " |____/|_|_| |_|\\__, |\\__,_|___/\n"
                + "                |___/           \n";

        //Message sequence
        System.out.println(line);
        System.out.print(banner);
        System.out.println("Hello! I'm Bingus.");
        System.out.println("What can I do for you?");
        System.out.println(line);

        Echo();
    }

    /**
     * Method to handle echo commands. Repeats the input and exist on {@code bye}
     */
    private static void Echo() {
        Scanner scanner = new Scanner(System.in);
        while(scanner.hasNextLine()) {
            String userInput = scanner.nextLine();
            System.out.println(line);
            if (userInput.equals("bye")) {
                System.out.println("Bye! Visit me again when you're free :) ");
                System.out.println(line);
                // Exit out of echo
                return;
            } else {
                System.out.println("  " + userInput);
                System.out.println(line);
            }
        }
    }
}
