import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/**
 * Starts Bingus and handles simple commands entered at the terminal.
 */
public class Bingus {

    private static final String LINE = "____________________________________________________________";
    private static final String INDENT = "    ";
    private static final Storage storage = new Storage("data/bingus.txt");

    /** Strict format accepted for deadline and event date/time input. */
    private static final DateTimeFormatter INPUT_DATE_TIME_FORMAT = DateTimeFormatter
            .ofPattern("uuuu-MM-dd HHmm")
            .withResolverStyle(ResolverStyle.STRICT);

    /** Strict format accepted when filtering tasks by date. */
    private static final DateTimeFormatter INPUT_DATE_FORMAT = DateTimeFormatter
            .ofPattern("uuuu-MM-dd")
            .withResolverStyle(ResolverStyle.STRICT);

    /** Format used when showing the selected date in a filtered task list. */
    private static final DateTimeFormatter DISPLAY_DATE_FORMAT =
            DateTimeFormatter.ofPattern("MMM d uuuu");

    private static final List<Task> inputList = new ArrayList<>();
    private static int inputListSize = 0;
    private static String loadErrorMessage;

    /**
     * Displays the welcome message and starts processing user commands.
     *
     * @param args command-line arguments, which are not used
     */
    public static void main(String[] args) {
        //String was generated by Codex based on an ASCII art input
        String banner = "  ____  _                       \n"
                + " | __ )(_)_ __   __ _ _   _ ___ \n"
                + " |  _ \\| | '_ \\ / _` | | | / __|\n"
                + " | |_) | | | | | (_| | |_| \\__ \\\n"
                + " |____/|_|_| |_|\\__, |\\__,_|___/\n"
                + "                |___/           \n";

        try {
            inputList.addAll(storage.loadTasks());
            inputListSize = inputList.size();
        } catch (BingusException e) {
            loadErrorMessage = "I couldn't load your save tasks, Sorry! Starting with an empty list";
        }

        //Message sequence
        System.out.println(LINE);
        System.out.print(banner);
        System.out.println("Hello! I'm Bingus.");
        System.out.println("What can I do for you?");
        System.out.println(LINE);
        if (loadErrorMessage != null) {
            System.out.println(INDENT + loadErrorMessage);
            System.out.println(LINE);
        }

        startTaskLoop();
    }

    /**
     * Read the command input from user and delegate to respective helper methods
     */
    private static void startTaskLoop() {
        Scanner scanner = new Scanner(System.in);
        while (scanner.hasNextLine()) {
            String userInput = scanner.nextLine();
            try {
                // Split into 2 parts, the command
                String[] parts = userInput.split("\\s+", 2);
                String command = parts[0];

                // parts must be size > 1, unless it's a bye command

                System.out.println(LINE);
                switch (command) {
                    case "bye":
                        exitChat();
                        return;
                    case "list":
                        handleList(parts);
                        break;
                    case "mark": {
                        handleMark(parts, true);
                        break;
                    }
                    case "unmark": {
                        handleMark(parts, false);
                        break;
                    }
                    case "todo": {
                        handleTodo(parts);
                        break;
                    }
                    case "deadline": {
                        handleDeadline(parts);
                        break;
                    }
                    case "event": {
                        handleEvent(parts);
                        break;
                    }
                    case "delete" : {
                        handleDelete(parts);
                        break;
                    }
                    default:
                        throw new BingusException("I don't recognise this command :/ ");
                }
            } catch (BingusException e) {
                System.out.println(INDENT + e.getMessage());
                System.out.println(LINE);
            }
        }
    }

    /**
     * Stores a task and displays its add confirmation.
     *
     * @param t task to store
     */
    private static void addTask(Task t) throws BingusException {
        inputList.add(t);
        inputListSize++;
        try {
            storage.saveTasks(inputList);
        } catch (BingusException e) {
            inputList.remove(inputListSize - 1);
            inputListSize--;
            throw e;
        }
        System.out.println(INDENT + "Got it. I've added this task:");
        System.out.println(INDENT + INDENT +  t.getTaskString());
        System.out.println(INDENT + "Now you have " + inputListSize + " tasks in the list.");
        System.out.println(LINE);
    }

    /**
     * Displays the farewell message.
     */
    private static void exitChat() {
        System.out.println(INDENT + "Bye! Visit me again when you're free :) ");
        System.out.println(LINE);
    }

    /**
     * Displays all tasks currently stored in the list.
     */
    private static void listTasks() {
        System.out.println(INDENT + "Here are the tasks in your list:");
        for (int id = 0; id < inputListSize; id++) {
            System.out.println(INDENT + (id + 1) + "." + inputList.get(id).getTaskString());
        }
        System.out.println(LINE);
    }

    /**
     * Lists all tasks, or dated tasks occurring on a requested date.
     *
     * @param parts command and optional date filter
     * @throws BingusException if the requested date is invalid
     */
    private static void handleList(String[] parts) throws BingusException {
        if (parts.length == 1) {
            listTasks();
            return;
        }

        try {
            LocalDate date = LocalDate.parse(parts[1].trim(), INPUT_DATE_FORMAT);
            listTasksOn(date);
        } catch (DateTimeParseException e) {
            throw new BingusException("Invalid list date. Please use yyyy-MM-dd, e.g. 2019-12-02.");
        }
    }

    /**
     * Displays deadlines due or events occurring on the specified date.
     *
     * @param date calendar date used to filter dated tasks
     */
    private static void listTasksOn(LocalDate date) {
        System.out.println(INDENT + "Here are the tasks on " + date.format(DISPLAY_DATE_FORMAT) + ":");
        for (int id = 0; id < inputListSize; id++) {
            Task task = inputList.get(id);
            if (occursOn(task, date)) {
                System.out.println(INDENT + (id + 1) + "." + task.getTaskString());
            }
        }
        System.out.println(LINE);
    }

    /**
     * Returns whether a dated task occurs on the specified date.
     *
     * @param task task to check
     * @param date calendar date to compare against
     * @return true if a deadline is due or an event overlaps the date
     */
    private static boolean occursOn(Task task, LocalDate date) {
        if (task instanceof Deadline) {
            Deadline deadline = (Deadline) task;
            return deadline.getBy().toLocalDate().equals(date);
        }
        if (task instanceof Event) {
            Event event = (Event) task;
            LocalDate startDate = event.getFrom().toLocalDate();
            LocalDate endDate = event.getTo().toLocalDate();
            return !date.isBefore(startDate) && !date.isAfter(endDate);
        }
        return false;
    }

    /**
     * Marks the task with the given user-facing number as complete.
     *
     * @param inputId one-based task number entered by the user
     */
    private static void markTask(int inputId) throws BingusException {
        // TODO: consider invalid inputId, to be done in future level
        Task task = inputList.get(inputId - 1);
        task.mark();
        try {
            storage.saveTasks(inputList);
        } catch (BingusException e) {
            task.unmark();
            throw e;
        }
        System.out.println(INDENT + "Nice! I've marked this task as done : ) ");
        System.out.println(INDENT + INDENT + task.getTaskString());
        System.out.println(LINE);
    }

    /**
     * Handle input validation before marking/unmarking a task
     *
     * @param parts  command + parameters as an array
     * @param isMark true if request to mark, false if request to unmark
     * @throws BingusException if taskId is invalid range or not a number
     */
    private static void handleMark(String[] parts, boolean isMark) throws BingusException {
        if (parts.length < 2){
            String action = (isMark ? "Mark": "Unmark");
            throw new BingusException(action+" must be followed by a number!");
        }
        try {
            String input = parts[1];
            int taskId = Integer.parseInt(input.trim());
            if (taskId < 1 || taskId > inputListSize) {
                throw new BingusException("Given task number does not exist in your list :(");
            }
            if (isMark) {
                markTask(taskId);
            } else {
                unmarkTask(taskId);
            }
        } catch (NumberFormatException e) {
            throw new BingusException("Invalid mark command! Usage: `mark [TASK_NUMBER]`");
        }
    }

    /**
     * Marks the task with the given user-facing number as incomplete.
     *
     * @param inputId one-based task number entered by the user
     */
    private static void unmarkTask(int inputId) throws BingusException {
        Task task = inputList.get(inputId - 1);
        task.unmark();
        try {
            storage.saveTasks(inputList);
        } catch (BingusException e) {
            task.mark();
            throw e;
        }
        System.out.println(INDENT + "OK, I've marked this task as not done yet: ");
        System.out.println(INDENT + INDENT + task.getTaskString());
        System.out.println(LINE);
    }

    private static void handleTodo(String[] parts) throws BingusException {
        if (parts.length < 2) {
            throw new BingusException("Please give your todo a task description! Usage `todo [DESCRIPTION]`.");
        }
        String desc = parts[1].trim();
        if (desc.isEmpty()) {
            throw new BingusException("Please give your todo a task description! Usage `todo [DESCRIPTION]`.");
        }
        addTask(new Todo(desc));
    }

    private static void handleDeadline(String[] parts) throws BingusException {
        String correctFormatMessage = "Please use `deadline [DESCRIPTION] /by [DATETIME]`.";
        if (parts.length < 2) {
            throw new BingusException("Missing command arguments :( " + correctFormatMessage);
        }
        // Format: [desc] /by [date]
        String[] split = parts[1].split("/by");
        if (split.length != 2) {
            throw new BingusException("Wrong format for deadline :( " + correctFormatMessage);
        }
        String taskDesc = split[0].trim();
        String by = split[1].trim();
        if (taskDesc.isEmpty()) {
            throw new BingusException("Task description cannot be empty. " + correctFormatMessage);
        }
        if (by.isEmpty()){
            throw new BingusException("Deadline cannot be empty. " + correctFormatMessage);
        }
        try {
            LocalDateTime deadlineDateTime = LocalDateTime.parse(by, INPUT_DATE_TIME_FORMAT);
            addTask(new Deadline(taskDesc, deadlineDateTime));
        } catch (DateTimeParseException e) {
            throw new BingusException("Invalid deadline date/time. Please use yyyy-MM-dd HHmm, "
                    + "e.g. 2019-12-02 1800.");
        }
    }

    private static void handleEvent(String[] parts) throws BingusException {
        String correctFormatMessage = "Please use `event [DESCRIPTION] /from [FROM_DATE] /to [TO_DATE]`";
        if (parts.length < 2) {
            throw new BingusException("Missing event arguments :( " + correctFormatMessage);
        }
        String[] descAndTimes = parts[1].split("/from");
        if (descAndTimes.length != 2) {
            throw new BingusException(correctFormatMessage);
        }

        String[] startAndEnd = descAndTimes[1].split("/to");
        if (startAndEnd.length != 2){
            throw new BingusException(correctFormatMessage);
        }
        String desc = descAndTimes[0].trim();
        String from = startAndEnd[0].trim();
        String to = startAndEnd[1].trim();
        if (from.isEmpty()){
            throw new BingusException("From cannot be empty! " + correctFormatMessage);
        }
        if (to.isEmpty()){
            throw new BingusException("`To` cannot be empty! " + correctFormatMessage);
        }
        if (desc.isEmpty()){
            throw new BingusException("`Description` of event cannot be empty! " + correctFormatMessage);
        }
        try {
            LocalDateTime fromDateTime = LocalDateTime.parse(from, INPUT_DATE_TIME_FORMAT);
            LocalDateTime toDateTime = LocalDateTime.parse(to, INPUT_DATE_TIME_FORMAT);
            if (!toDateTime.isAfter(fromDateTime)) {
                throw new BingusException("Event end date/time must be after its start date/time.");
            }
            addTask(new Event(desc, fromDateTime, toDateTime));
        } catch (DateTimeParseException e) {
            throw new BingusException("Invalid event date/time. Please use yyyy-MM-dd HHmm, "
                    + "e.g. 2019-12-02 1800.");
        }
    }

    private static void handleDelete(String[] parts) throws BingusException {
        if (parts.length < 2) {
            throw new BingusException("Missing delete number! Usage `delete [TASK_NUMBER]`. ");
        }
        try {
            String input = parts[1];
            int taskId = Integer.parseInt(input.trim());
            if (taskId < 1 || taskId > inputListSize) {
                throw new BingusException("Given task number does not exist in your list :(");
            }
            // call delete function
            delete(taskId);
        } catch (NumberFormatException e) {
            throw new BingusException("Invalid mark command! Usage: `mark [TASK_NUMBER]`");
        }
    }

    private static void delete(int pos) throws BingusException {
        Task t = inputList.get(pos - 1);
        inputList.remove(pos - 1);
        inputListSize--;
        try {
            storage.saveTasks(inputList);
        } catch (BingusException e) {
            inputList.add(pos - 1, t);
            inputListSize++;
            throw e;
        }
        System.out.println(INDENT + "Noted! I've removed this task: ");
        System.out.println(INDENT + INDENT + t.getTaskString());
        System.out.println("Now you have " + inputListSize + " tasks in the list.");
        System.out.println(LINE);
    }


}
